In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import Series, DataFrame

In [62]:
pd.options.display.max_rows=3000


df = pd.read_csv('data.csv')

s = "Q"
columns = []
for i in range(1, 29):
    columns.append(s + str(i))
    
df[columns] = df[columns].replace([1, 2, 3, 4, 5], [-2, -1, 0, 1, 2])
df["sum"] = df[columns].sum(axis=1).div(28)
df2 = df[df["Q1"] != df["sum"]]
#df2


attendance = df["attendance"].sum()

float_att = float(attendance)

courseQ = ['Q11', 'Q4', 'Q9','Q10',]

instrQ = ['Q15','Q16', 'Q13', 'Q19']

misc = ['attendance', 'nb.repeat', 'difficulty']

mergedQ = courseQ + instrQ + misc

table = pd.pivot_table(df2, values=mergedQ, 
                    index=['instr', 'class'],
                    aggfunc=np.mean)

table['Course question sum'] = table[courseQ].sum(axis=1).div(4)
table['Instructor question sum'] = table[instrQ].sum(axis=1).div(4)
table['Difference'] = (table['Course question sum'] - table['Instructor question sum'])


table
# mergedQ

                  Q10       Q11       Q13       Q15       Q16       Q19  \
instr class
1     2      0.325581  0.395349  0.674419  0.697674  0.488372  0.604651
      7      0.000000  0.584158  0.326733  0.485149  0.168317  0.435644
      10     0.292398  0.421053  0.368421  0.368421  0.292398  0.345029
2     1      0.278195  0.518797  0.556391  0.533835  0.496241  0.593985
      6      0.280156  0.400778  0.645914  0.634241  0.583658  0.614786
      11     0.072398  0.248869  0.366516  0.502262  0.235294  0.556561
      13    -0.016667  0.233333  0.483333  0.666667  0.550000  0.750000
3     3     -0.208108 -0.208108  0.151351  0.202703 -0.051351  0.070270
      4     -0.393162 -0.145299  0.119658  0.094017 -0.213675 -0.059829
      5     -0.107042 -0.188732  0.267606  0.360563  0.090141  0.183099
      8     -0.106383  0.510638  0.240122  0.501520 -0.018237  0.462006
      9     -0.059441  0.437063  0.181818  0.402098  0.017483  0.265734
      12    -0.117647  0.235294  0.294118  0.235294  0.235294  0.705882
      13    -0.280236 -0.312684 -0.035398 -0.017699 -0.126844  0.032448

                   Q4        Q9  attendance  difficulty  nb.repeat  \
instr class
1     2     -0.023256  0.325581    1.976744    3.302326   1.139535
      7     -0.059406  0.128713    2.455446    3.900990   1.227723
      10     0.228070  0.286550    2.017544    2.684211   1.076023
2     1      0.142857  0.413534    1.887218    2.518797   1.172932
      6      0.143969  0.264591    1.887160    2.575875   1.155642
      11     0.045249  0.348416    2.076923    3.176471   1.099548
      13     0.133333  0.366667    1.950000    2.166667   1.033333
3     3     -0.151351 -0.127027    1.602703    3.072973   1.172973
      4     -0.649573  0.076923    1.786325    2.948718   1.264957
      5      0.050704 -0.061972    1.836620    3.030986   1.092958
      8     -0.179331  0.194529    2.291793    3.136778   1.243161
      9     -0.041958  0.143357    1.762238    2.793706   1.335664
      12     0.294118  0.411765    2.117647    3.000000   1.176471
      13    -0.309735 -0.117994    1.448378    2.545723   1.351032

             Course question sum  Instructor question sum  Difference
instr class
1     2                 0.255814                 0.616279   -0.360465
      7                 0.163366                 0.353960   -0.190594
      10                0.307018                 0.343567   -0.036550
2     1                 0.338346                 0.545113   -0.206767
      6                 0.272374                 0.619650   -0.347276
      11                0.178733                 0.415158   -0.236425
      13                0.179167                 0.612500   -0.433333
3     3                -0.173649                 0.093243   -0.266892
      4                -0.277778                -0.014957   -0.262821
      5                -0.076761                 0.225352   -0.302113
      8                 0.104863                 0.296353   -0.191489
      9                 0.119755                 0.216783   -0.097028
      12                0.205882                 0.367647   -0.161765
      13               -0.255162                -0.036873   -0.218289